const express = require('express')
const bodyParser = require('body-parser')
const cors = require('cors')
const app = express()
const apiPort = 3000
const db = require('./db')
const userRoutes = require('./routes/userRoutes')
app.use(bodyParser.urlencoded({ extended: true }))
app.use(cors())
app.use(bodyParser.json())
app.use('/api', userRoutes)
app.get('/server', (req, res) => {
 res.send('Hello World!')
})
db.on('error', console.error.bind(console, 'MongoDB connection error:'))
app.listen(apiPort, () => console.log(`Server running on port ${apiPort}`))